### ISSUE TITLE
torch GPU deployment get nvrtc: error

### ISSUE THREAD

**Issue by yashenkoxciv** [RedisAI/RedisAI#887]
I am trying to use redislabs/redisai:1.2.5-gpu-bionic docker image for tests.

So I did
`docker run -p 6379:6379 -v /home/aaaa/data/rdb:/data --gpus all -it --rm redislabs/redisai:1.2.5-gpu-bionic`

My OS is Ubuntu 20.04.3 (focal) by the way.

Then I deployed my model using this code:
`
con.modelstore(
    'my_model', 'torch', 'gpu', pt_model,
    batch=5, minbatch=1, minbatchtimeout=70
)
`
It successfully added.
Next I am trying to do:

```
rai_con.tensorset('image', image_tensor)

rai_con.scriptexecute('my_model_script', 'pre_process', inputs=['image'], outputs=['temp1'])

rai_con.modelexecute('my_model', ['temp1'], ['temp2'])

rai_con.scriptexecute('my_model_script', 'post_process', inputs=['temp2'], outputs=['out'])

label = rai_con.tensorget('out')

```
and got the error
`redis.exceptions.ResponseError: nvrtc: error: failed to open libnvrtc-builtins.so.11.1.   Make sure that libnvrtc-builtins.so.11.1 is installed correctly. nvrtc compilation failed:   #define NAN __int_as_float(0x7fffffff) #define POS_INFINITY __int_as_float(0x7f800000) #define NEG_INFINITY __int_as_float(0xff800000)   template<typename T> __device__ T maximum(T a, T b) {   return isnan(a) ? a : (a > b ? a : b); }  template<typename T> __device__ T minimum(T a, T b) {   return isnan(a) ? a : (a < b ? a : b); }  extern "C" __global__ void fused_cat_batch_norm(float* tweight_16, float* tbias_8, float* trunning_mean_8, float* trunning_var_8, float* tinit_features_2, float* aten_batch_norm) { {   float trunning_var_8_1 = __ldg(trunning_var_8 + ((512 * blockIdx.x + threadIdx.x) / 3136) % 64);   float tweight_16_1 = __ldg(tweight_16 + ((512 * blockIdx.x + threadIdx.x) / 3136) % 64);   double v = (double)(__ldg(tinit_features_2 + (512 * blockIdx.x + threadIdx.x) % 200704));   double v_1 = (double)(__ldg(tbias_8 + ((512 * blockIdx.x + threadIdx.x) / 3136) % 64));   double v_2 = (double)(__ldg(trunning_mean_8 + ((512 * blockIdx.x + threadIdx.x) / 3136) % 64));   aten_batch_norm[512 * blockIdx.x + threadIdx.x] = (float)(v * ((rsqrt((double)(trunning_var_8_1) + 1e-05)) * (double)(tweight_16_1)) + (v_1 - v_2 * ((rsqrt((double)(trunning_var_8_1) + 1e-05)) * (double)(tweight_16_1)))); } } 
`
on the line: rai_con.modelexecute('my_model', ['temp1'], ['temp2'])

I installed cuda-toolkit with: sudo apt install nvidia-cuda-toolkit. But it did not help.

Please help.

**Comment by DvirDukhan** [comment]
hi @yashenkoxciv 
Thanks for reporting
Can you provide some additional details?
1. What is the cuda version on the host machine?
2. Version of pytorch you used to generate/trace your model?
3. If possible - share the model you tried to upload

Thanks

**Comment by yashenkoxciv** [comment]
Hi @DvirDukhan 
Here are details:

1. What is the cuda version on the host machine?
I reinstalled different versions of drivers and cuda. Now it is:
Driver Version: 460.91.03, CUDA Version: 11.2

2. Version of pytorch you used to generate/trace your model?
torch==1.10.1+cu113

3. The model I tried to upload:
https://drive.google.com/file/d/1On7_xNzGPwIvVH3CKWDaluoHZMAV22qz/view?usp=sharing

I see that current host CUDA version and torch CUDA version are not the same. I tried 11.3 too.

**Comment by yashenkoxciv** [comment]
This model is compiled densenet121 from torchvision.

**Comment by DvirDukhan** [comment]
@yashenkoxciv sorry for the delay, I missed your previous reply.
1. Please try to trace/export with pytorch 1.9. RedisAI 1.2.5 is bundled with pytorch 1.9, so let's verify/revoke compatibility issues.
2. With respect to 1, I'm now working on pytorch 1.10 bundling to be done this/next week at #888  , to be delivered with RedisAI 1.2.6.
Thanks

**Comment by yashenkoxciv** [comment]
@DvirDukhan thanks for answering!

I trained and exported the network (densenet121) again with torch==1.9.0+cu111.
Deployed the model to RedisAI 1.2.5 and got the same error:
`redis.exceptions.ResponseError: nvrtc: error: failed to open libnvrtc-builtins.so.11.1.   Make sure that libnvrtc-builtins.so.11.1 is installed correctly. nvrtc compilation failed: ...`

Interesting fact, I trained resnet18 to replace previous model and it worked!
5 test requests passed!

Summary: I reinstalled the environment with torch==1.9.0+cu111. Trained densenet121 and got the same problem.
In the same environment I trained resnet18 and it works well. So second inference call on densenet121 failed with the error and resnet18 worked.

In the links below I found that there is JIT fusers that probably use nvrtc. Also I did not find nvrtc in redislabs/redisai:1.2.5-gpu-bionic docker image. Maybe it should be there? (see link number 3)

I have found some interesting links about the problem:

1. https://discuss.pytorch.org/t/second-forward-call-of-torchscripted-module-breaks-on-cuda/124291/5
2. https://pytorch.org/tutorials/recipes/fuse.html
3. https://ubuntu.pkgs.org/18.04/ubuntu-multiverse-amd64/libnvrtc9.1_9.1.85-3ubuntu1_amd64.deb.html

**Comment by yashenkoxciv** [comment]
Ok. It looks like the problem is solved.

I tried to save model (densenet121) using this code:
```
scripted_model = torch.jit.script(model)
torch.jit.save(scripted_model, model_filename)
```
and it worked!

Previously I used this code to save model:
```
traced = torch.jit.trace(model, inputs)
traced.save(model_filename)
```
and I received that error with nvrtc when I tried to run the model using RedisAI. 

I am going to learn the difference.

Thank you @DvirDukhan !

**Comment by DvirDukhan** [comment]
@yashenkoxciv can you please provide an end-to-end reproduction script? I want to dig a little bit myself
Thanks
